### PR TITLE
add missing column in metadata_items

### PR DESCRIPTION
**Pull request by daxxi13**
add missing column in metadata_items1 and metadata_items2

### CODE REVIEW

**Review by sh4des — APPROVED** [review]
LGTM - just tested the changes and the script works as intended again. Thanks

**Comment by Fmstrat** [comment]
So I'll merge this in shortly, but any chance you would be willing to include a "column check" to see if there are changes in the existing database tables and error out if so?

**Comment by daxxi13** [comment]
> So I'll merge this in shortly, but any chance you would be willing to include a "column check" to see if there are changes in the existing database tables and error out if so?

we can compare version of database PLEXDB1 and PLEXDB2 (echo "select version from schema_migrations order by version desc limit 1;" | sqlite3 "${PLEXDB1}")
and then create tables on tmpdb with PLEXDB1 schema (sqlite3  "${PLEXDB1}" ".schema metadata_items"|grep CREATE\ TABLE |sed -e 's,CREATE TABLE IF NOT EXISTS "metadata_items",CREATE TABLE IF NOT EXISTS "metadata_items1",g'| sqlite3 "${TMPDB}")

**Comment by Fmstrat** [comment]
Perfect, thanks!

**Pull request merged**
